name: Lint

on:
    workflow_call:

jobs:
    lint:
        runs-on: [ubuntu-latest]
        name: Lint
        steps:
            - uses: actions/checkout@v7
              name: Checkout repository

            - uses: actions/setup-node@v6
              name: Setup node
              with:
                  node-version: latest

            - uses: pnpm/action-setup@v6
              name: Setup pnpm
              with:
                  version: latest

            - run: pnpm install
              name: Install dependencies

            - run: pnpm run lint
              name: Lint
