name: Type check

on:
    workflow_call:

jobs:
    type_check:
        runs-on: [ubuntu-latest]
        name: Type check
        steps:
            - uses: actions/checkout@v6
              name: Checkout repository

            - uses: actions/setup-node@v6
              name: Setup node

            - uses: pnpm/action-setup@v6
              name: Setup pnpm

            - run: pnpm install
              name: Install dependencies

            - run: pnpm run type-check
              name: Type check
